<!DOCTYPE html>
<html>
	<head>
		<title>KVH TVRO</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0" />

		<meta http-equiv="cache-control" content="max-age=0" />
		<meta http-equiv="cache-control" content="no-cache" />
		<meta http-equiv="expires" content="0" />
		<meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
		<meta http-equiv="pragma" content="no-cache" />

		<link type="text/css" rel="stylesheet" href="/css/support.css">


		<script type="text/javascript" src="/js/jquery-1.10.2.min.js"></script>
		<script type="text/javascript" src="/js/base.js"></script>

		<script type="text/javascript" src="/js/lodash.min.js"></script>
		<script src="/js/promise-3.2.0.js"></script>

		<script type="text/javascript" src="/js/tvro.js"></script>
		<script type="text/javascript" src="/js/webservice.js"></script>
		<script type="text/javascript" src="/js/data.js"></script>
		<script type="text/javascript" src="/js/table.js"></script>
		<script type="text/javascript" src="/js/insSatView.js"></script>
		<script type="text/javascript" src="/js/satTable.js"></script>
		<script type="text/javascript" src="/js/satInfoView.js"></script>
		<script type="text/javascript" src="/js/satEditView.js"></script>
		<script type="text/javascript" src="/js/groupTable.js"></script>
		<script type="text/javascript" src="/js/groupInfoView.js"></script>
		<script type="text/javascript" src="/js/groupEditView.js"></script>
		<script type="text/javascript" src="/js/toggleBtn.js"></script>
		<script type="text/javascript" src="/js/dropdown.js"></script>

		<script type="text/javascript" src="/js/RestartSystemView.js"></script>
		<script type="text/javascript" src="/js/OperationalLogView.js"></script>
		<script type="text/javascript" src="/js/CmdLineView.js"></script>
		<script type="text/javascript" src="/js/EventLogView.js"></script>
		<script type="text/javascript" src="/js/support.js"></script>

	</head>

	<body>

<!-- header/nav
- -- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<div class="header #header">
	<div class="status-btn #status-btn">Status</div>
	<div class="nav-btn #nav-btn">Menu</div>
	<div class="tracvision-logo"></div>
</div>

<div class="nav #nav">
	<a href="/home.php" class="home-btn #home-btn">Home</a>
	<a href="/satellites.php" class="sat-btn #sat-btn">Satellites</a>
	<a href="/autoswitch.php" class="autoswitch-btn #autoswitch-btn">Autoswitch</a>
	<a href="/settings.php" class="settings-btn #settings-btn">Settings</a>
	<a href="/updates.php" class="updates-btn #updates-btn">Updates</a>
	<a href="/support.php" class="support-btn #support-btn">Support</a>
</div>

<!-- sidebar
- -- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<div class="sidebar">

	<div class="menu-table #menu-table-view">
		<div class="table-row #table-row">
			<div class="table-col #menu-item"></div>
		</div>
	</div>

	<div class="contact-header">Technical Support</div>

	<div class="contact-region">North/South America, Australia, New Zealand</div>
	<a href="mailto:support@kvh.com" class="block-btn">support@kvh.com</a>
	<a href="tel:+1 (401) 847-3327" class="block-btn">+1 401 847-3327</a>

	<div class="contact-region">Africa, Asia, Europe, Middle East</div>
	<a href="mailto:support@emea.kvh.com" class="block-btn">support@emea.kvh.com</a>
	<a href="tel:+45 45 160 180" class="block-btn">+45 45 160 180</a>

</div>

<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<div class="view operational-log #operational-log-view">
	<div class="view-head">
		Operational Log
		<div class="back-btn #back-btn"></div>
	</div>

	<p>When initiated, the Operational Log records all messages generated by the
	antenna system.</p>

	<div class="block-btn view-curr-log-btn #view-btn">
		View Current Log
	</div>

	<p>Choose this option to view the current Operational Log.</p>

	<div class="block-btn start-new-log-btn #start-btn">
		Start New Log
	</div>

	<p>Choose this option to delete the current Operational Log and begin
	recording a new one.</p>

	<div class="block-btn restart-btn #restart-btn">
		Restart System & Start New Log
	</div>

	<p>Choose this option to delete the current Operational Log, restart the
	antenna, and begin recording a new Operational Log that includes startup
	self-test results. This information is very useful for diagnostics.</p>

	</div>
</div>

<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<div class="view event-log #event-log-view">
	<div class="view-head">
		Event Log
		<div class="back-btn #back-btn"></div>
	</div>

	<p>The Event Log keeps a historical record of all major system events, including any error messages generated by the system.</p>

	<div class="event-table #event-table-view">
		<div class="table-head #table-head">
			<div class="table-col date-col #event-date">Date/Time</div><!--
		--><div class="table-col message-col message #event-message">Message</div>
		</div>
		<div class="table-row #table-row">
			<div class="table-col date-col #event-date"></div><!--
		--><div class="table-col message-col message #event-message"></div>
		</div>
	</div>

	<div class="btn-tray">
		<div id="" class="block-btn save-btn #save-btn">Save Log</div>
		<div id="" class="block-btn email-btn #email-btn">Email Log</div>
 	</div>

</div>

<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<div class="view restart-system #restart-system-view">
	<div class="view-head">
		Restart System
		<div class="back-btn #back-btn"></div>
	</div>

	<div class="block-btn restart-hub-btn #system-btn">
		Restart TV-Hub
	</div>

	<p>Choose this option to restart just the TV-Hub.</p>

	<div class="block-btn restart-ant-btn #antenna-btn">
		Restart Antenna
	</div>

	<p>Choose this option to restart just the antenna.</p>

	<div class="block-btn restart-all-btn #all-btn">
		Restart All
	</div>

	<p>Choose this option to restart the entire system, both TV-Hub and antenna.</p>

</div>

<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<div class="view command-line #command-line-view">
	<div class="view-head">
		Command Line
		<div class="back-btn #back-btn"></div>
	</div>

	<p>Improper use of antenna commands can directly impact performance.
	Only KVH-authorized technicians should use this interface.</p>

	<!-- src set in CmdLineView -->
	<iframe src="" class="output #output"></iframe>
	<div class="btn-tray">
		<input placeholder="Enter your commands here." class="input #input" /><!--
	--><div class="block-btn #send-btn">Send</div>
	</div>
</div>

<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	</body>
</html>